export enum OrderCode {

  BY_DATE_ASCENDING = 'BY_DATE_ASCENDING',
  BY_DATE_DESCENDING = 'BY_DATE_DESCENDING',
  BY_SEVERITY_ASCENDING = 'BY_SEVERITY_ASCENDING',
  BY_SEVERITY_DESCENDING = 'BY_SEVERITY_DESCENDING',
  BY_DISTANCE_ASCENDING = 'BY_DISTANCE_ASCENDING',
  BY_DISTANCE_DESCENDING = 'BY_DISTANCE_DESCENDING'

}
